### PR TITLE
New getSongByID() method

### PR DESCRIPTION
**Pull request by abhishrant**
Hello Devs,

Since I need to get a song by a song ID and it was not available in the library so I edited the library and added a new method getSongByID() to Client class

function getSongByID(song_id)
           return Song Object

Thank You,

### CODE REVIEW

**Comment by koehlma** [comment]
Hi there,

I think there should be a better way to implement this, requesting a stream token and then use that token to request a song object is not a good idea and produces much overhead. There should really be a direct api request to accomplish that.

**Comment by abhishrant** [comment]
I an still trying to search for a direct method but can't find. Grooveshark catalogs the song by token instead of ID (i might be wrong).

The function seems to handle it pretty nicely. Takes not much time but i am still looking for another way to bypass token.

I will give you an update when i get it. :D

Meanwhile if anyone needs it they can use it temporarily.

**Comment by koehlma** [comment]
I had some free time today to implement this using `getTokenForSong` so it's not neccessary to request a stream key for this. ;)

**Comment by abhishrant** [comment]
Great, I will update the module and change my code ASAP to test it out :D
Thank You,

**Pull request closed without merging**
